#pragma once

#include <iostream>
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

void fibonacci_even_terms_sum()
{
	int prev2 = 1, prev1 = 2;
	unsigned int sum = 2;

	int curr_fib = prev1 + prev2;
	int P[3];
	int p;
	P[0] = 1;
	P[1] = 1;
	P[2] = 2;
	p = 2;
	while (P[p] < 4000000)
	{
		if (P[p] % 2 == 0)
			sum += P[p];

		p = 1-p;
		P[p] = P[0] + P[1] + P[2] - P[p];
	}

	std::cout << "fibonacci_even_terms_sum: " << sum << std::endl;
}